apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-account
  annotations:
    # use the shared ingress-nginx
    # nginx.org/rewrites: "serviceName=backend rewrite=/;"
    # kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  # - host: codebit-172-17-187-91.nip.io
  # - host: api.cgi-w3.stackroute.io
  - host: codebit.app.cgi-w3.stackroute.io
    http:
      paths:
      - path: /account/?(.*)
        backend:
          serviceName: account_app
          servicePort: 80