apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: account_claim
  namespace: mashup
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: gp2
  resources:
    requests:
      storage: 5Gi
